* beeminder.el

A really simple Emacs extension for working with Beeminder.

This is very much in the early stages, so there's not really any error checking.

It's designed to integrate with org-mode, and adds support for submitting data
directly to Beeminder when a task is closed (see usage for some examples).

Thanks to Sacha Chua for providing the inspiration and initial code for this
extension: https://gist.github.com/sachac/9700455


** Installation

All Emacs installs are a little different, but the basic outline is this:

  - Download the source code and put it somewhere Emacs can find it (probably
    =~/.emacs.d/=)
  - Add that directory to your =load-path= if it's not yet there: =(add-to-list 'load-path "/path/to/dir")=
  - Add =(require 'beeminder)= somewhere in your =~/.emacs.d/init.el=
  - Set your API authorization token and Beeminder username configuration
    variables. You can find your token by logging into Beeminder and then visiting the following URI: https://www.beeminder.com/api/v1/auth_token.json
    To set it in Emacs, add the following code (or use =M-x customize=):

#+BEGIN_SRC emacs-lisp
(setq beeminder-username "username")
(setq beeminder-auth-token "token")
#+END_SRC
  
  - Set up your keyboard shortcuts. Here are some recommendations:

#+begin_src emacs-lisp
(global-set-key "\C-cba" 'beeminder-add-data)
(global-set-key "\C-cbw" 'beeminder-whoami)
(global-set-key "\C-cbg" 'beeminder-my-goals-org)
(global-set-key "\C-cbr" 'beeminder-refresh-goal)
(global-set-key "\C-cbt" 'beeminder-submit-clocked-time)
#+end_src    

** Usage

*** New Shortcuts

The recommended settings above will add the following keyboard shortcuts:

=C-c b a= (=beeminder-add-data=) - Add data to a Beeminder goal. Prompts for the goal identifier, a
numeric value and an optional comment.

=C-c b g= (=beeminder-my-goals-org=) - Fetches all of your goals from Beeminder and inserts them as a list
of org-mode headlines.

=C-c b w= (=beeminder-whoami=) - Fetches your username from Beeminder. Not really useful, but good
for checking if your authorization token is set and valid.

=C-c b t= (=beeminder-submit-clocked-time=) - Submits clocked time for the
current goal (and any of its sub-tasks). Only counts time from the "updated-at"
value of the goal.

*** Integrating with org-mode

This extension listens for changes to the state of org-mode todo items, and can
automatically add data to Beeminder once a task is complete. In order to do
this, the task (or its ancestors) must have a "=beeminder=" property that is set
to the name of the goal to add to.

Tasks can also set a "=value=" property, which will be sent when the task is
complete. If no "=value=" property is set, the value will default to 1.

Here's an example:

#+BEGIN_SRC org
,* Beeminder.el Tasks
   :PROPERTIES:
   :beeminder: beeminder-el
   :END:
,** TODO Write documentation
#+END_SRC

When "Write documentation" is changed to "DONE", =beeminder.el= will submit a
value of "1" to the "=beeminder-el=" goal.


** Future Improvements / TODO 

*** TODO Add a way to create goals on Beeminder from an org-mode headline
*** TODO Add some error checking!

** Licence

Copyright (C) 2014  Phil Newton

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
